server: 
  port: 8080  
  tomcat:
    max-threads: 50
mso:
  infra:
    auditInventory: false
spring: 
  datasource:
    hikari:
      jdbcUrl: jdbc:mariadb://127.0.0.1:3306/camundabpmn
      username: root
      password: root
      driver-class-name: org.mariadb.jdbc.Driver
      pool-name: bpmn-pool
      registerMbeans: true
  http:
    multipart:
      enabled: false
  jersey:
    application-path: /sobpmnengine
  main:
    allow-bean-definition-overriding: true
camunda:
  bpm:
    application:
      delete-upon-undeploy: false
      scan-for-process-definitions: true
      deploy-changed-only: true
    job-execution:
      deployment-aware: true
#Actuator
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
  metrics:
    se-global-registry: false
    export:
      prometheus:
        enabled: true # Whether exporting of metrics to Prometheus is enabled.
        step: 1m # Step size (i.e. reporting frequency) to use.
